/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.gerenciador;

/**
 *
 * @author Henrique
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
        setLocationRelativeTo(null);
        txtLista.setText(tarefa.mostrarLista());
    }

    Tarefa tarefa = new Tarefa();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAdicionar = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtExterminar = new javax.swing.JTextField();
        btnExterminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnExterminioTotal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAlterar = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        txtIndice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setText("GERENCIADOR DE TAREFAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 13)); // NOI18N
        jLabel2.setText("COLOQUE O INDICE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        txtAdicionar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        getContentPane().add(txtAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 282, -1));

        btnAdicionar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel3.setText("EXTERMINAR TAREFA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, -1, -1));

        txtExterminar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        getContentPane().add(txtExterminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 130, 290, -1));

        btnExterminar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnExterminar.setText("EXTERMINAR");
        btnExterminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExterminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnExterminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        txtLista.setColumns(20);
        txtLista.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        txtLista.setRows(5);
        jScrollPane1.setViewportView(txtLista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 654, 331));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel4.setText("LISTA DE TAREFA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        btnExterminioTotal.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnExterminioTotal.setText("EXTERMINAR TODAS AS TAREFAS");
        btnExterminioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExterminioTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnExterminioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 780, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel5.setText("ALTERAR");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        txtAlterar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        getContentPane().add(txtAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 282, -1));

        btnAlterar.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        txtIndice.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        getContentPane().add(txtIndice, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 282, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 13)); // NOI18N
        jLabel6.setText("ADICIONAR TAREFA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Light", 1, 13)); // NOI18N
        jLabel7.setText("COLOQUE O NOVO NOME");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic Light", 1, 13)); // NOI18N
        jLabel8.setText("COLOQUE O INDICE");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic Light", 1, 13)); // NOI18N
        jLabel9.setText("COLOQUE O NOME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnOrdenar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        btnOrdenar.setText("ORDENAR");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        getContentPane().add(btnOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        tarefa.adicionar(txtAdicionar.getText());
        txtLista.setText(tarefa.mostrarLista());
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int indice = Integer.parseInt(txtExterminar.getText());
        tarefa.alterar(indice, txtAlterar.getText());
        txtLista.setText(tarefa.mostrarLista());

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExterminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExterminarActionPerformed
        int indice = Integer.parseInt(txtExterminar.getText());
        tarefa.remover(indice);
        txtLista.setText(tarefa.mostrarLista());
    }//GEN-LAST:event_btnExterminarActionPerformed

    private void btnExterminioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExterminioTotalActionPerformed
        tarefa.removerTudo();
        txtLista.setText(tarefa.mostrarLista());
    }//GEN-LAST:event_btnExterminioTotalActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        tarefa.ordenar();
        txtLista.setText(tarefa.mostrarLista());
        new FrPopUp();
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExterminar;
    private javax.swing.JButton btnExterminioTotal;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAdicionar;
    private javax.swing.JTextField txtAlterar;
    private javax.swing.JTextField txtExterminar;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextArea txtLista;
    // End of variables declaration//GEN-END:variables
}
